<?php

return [
    
    /*
    |--------------------------------------------------------------------------
    | Composer File Template
    |--------------------------------------------------------------------------
    |
    | Here is the config for the composer.json file, generated by this package
    |
    */

    'composer' => [
        'vendor' => 'koverae',
        'author' => [
            'name' => 'Arden BOUET',
            'email' => 'laudbouetoumoussa@gmail.com',
        ],
        'composer-output' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Caching
    |--------------------------------------------------------------------------
    |
    | Here is the config for setting up the caching feature.
    |
    */
    'cache' => [
        'enabled' => false,
        'driver' => 'file',
        'key' => 'koverae-builder',
        'lifetime' => 60,
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Layout
    |--------------------------------------------------------------------------
    |
    | Path to your default layout
    |
    */

    'default_layout' => 'layouts.app',

    /*
    |--------------------------------------------------------------------------
    | Page Maker Configuration
    |--------------------------------------------------------------------------
    |
    | Here is the config for the page generation
    |
    */
    'page_maker' => [

        'namespace' => 'App\\Livewire\\Page',

        'default_path' => 'Livewire/Page/',

        'default_view_path' => 'views/livewire/page/',

        'default_tag_path' => 'livewire.page.',
        
        // Other page maker related settings can be added here as needed.
    ],

    /*
    |--------------------------------------------------------------------------
    | Form Maker Configuration
    |--------------------------------------------------------------------------
    |
    | Here is the config for the form generation
    |
    */

    'form_maker' => [

        'namespace' => 'App\\Livewire\\Form',

        'default_path' => 'Livewire/Form/',

        'default_view_path' => 'views/livewire/form/',

        'default_tag_path' => 'livewire.form.',
        
        // Other form maker related settings can be added here as needed.
    ],

    /*
    |--------------------------------------------------------------------------
    | Table Maker Configuration
    |--------------------------------------------------------------------------
    |
    | Here is the config for the table generation
    |
    */
    'table_maker' => [

        'namespace' => 'App\\Livewire\\Table',

        'default_path' => 'Livewire/Table/',

        'default_view_path' => 'views/livewire/table/',

        'default_tag_path' => 'livewire.table.',
        
        // Other table maker related settings can be added here as needed.
    ],

    /*
    |--------------------------------------------------------------------------
    | Control Panel Maker Configuration
    |--------------------------------------------------------------------------
    |
    | Here is the config for the control panel generation
    |
    */
   
    'control_panel_maker' => [

        'namespace' => 'App\\Livewire\\Navbar\\ControlPanel',

        'default_path' => 'Livewire/Navbar/ControlPanel/',

        'default_view_path' => 'views/livewire/navbar/control-panel/',

        'default_tag_path' => 'livewire.navbar.control-panel.',
        
        // Other control-panel maker related settings can be added here as needed.
    ],

    /*
     * Default layout for your package views.
     * You can specify the path to a Blade layout that will be used
     * as the base layout for all package views.
     */


];